a.exe: main.o pregame.o game.o postgame.o
	gcc -o main. pregame.0 game.o postgame.o

main.o: main.c
	gcc -g -c main.c

pregame.o: pregame.c
	gcc -g -c pregame.c

game.o: game.c
	gcc -g -c game.c

postgame.o: postgame.c
	gcc -g -c postgame.c

clean:
	del a.exe main.o pregame.o game.o postgame.o